version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-local
    ports:
      - "8000:8000"
    volumes:
      - ./data/chromadb:/chroma/data
    environment:
      - PERSIST_DIRECTORY=/chroma/data
      - ANONYMIZED_TELEMETRY=false
    networks:
      - rag-network

  rag-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rag-api-local
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
      - ./data:/data
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_API_KEY=${RAG_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - chromadb
    networks:
      - rag-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  rag-network:
    driver: bridge